### ISSUE TITLE
Split the completions directory and rename scripts according to conventions of each shell

### ISSUE THREAD

**Issue by schtobia** [ogham/exa#451]
First of all, thanks a lot for this great tool!

Would it be possible to split the [`/contrib`](/ogham/exa/tree/master/contrib) subdirectory for each shell? This way, I could add the completions script easily via [antigen](/zsh-users/antigen): `antigen bundle ogham/exa contrib/completions/zsh`.

Thanks again!

**Comment by schtobia** [comment]
I've committed an example at [my repo](/schtobia/exa/tree/split-subdirectories).

**Comment by ogham** [comment]
I know this issue is ooooold, but I've since [moved the completions out of `contrib/`](https://github.com/ogham/exa/tree/master/completions), since completions are the only shell-dependent files. Does antigen still have this requirement?

**Comment by ariasuni** [comment]
If I understand correctly [antigen’s documentation](https://github.com/zsh-users/antigen/wiki/Commands), I believe the problem is the same as #585, and that the fix is to use a structure similar [Homebrew/brew](https://github.com/Homebrew/brew/tree/master/completions), with a directory for each shell, and `exa.zsh` renamed `_exa` (since it should be installed under that name).

Then, `antigen bundle ogham/exa completions/zsh` should work.
